# Copyright 2026 ACSONE SA/NV (https://www.acsone.eu)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
from odoo.addons.queue_job.tests.common import trap_jobs

from .common import TestLocationOrderpointCommon


class TestCancelFulfilledReplenishment(TestLocationOrderpointCommon):
    def _create_not_started_replenishment_move(
        self, orderpoint, location_src, qty, picking_id=False
    ):
        """Simulate a replenishment move generated by the orderpoint that has
        not been assigned yet (no stock available at the source location)."""
        if not picking_id:
            picking_type = orderpoint.route_id.rule_ids.picking_type_id
            picking = self.env["stock.picking"].create(
                {
                    "picking_type_id": picking_type.id,
                    "location_id": location_src.id,
                    "location_dest_id": self.location_dest.id,
                }
            )
            picking_id = picking.id
        move = self._create_move(
            "Auto replenishment",
            qty,
            location_src,
            self.location_dest,
            location_orderpoint_id=orderpoint.id,
            picking_id=picking_id,
        )
        self.assertEqual(move.state, "confirmed")
        return move

    def test_cancel_when_demand_is_fully_fulfilled(self):
        orderpoint, location_src = self._create_orderpoint_complete(
            "Stock2", trigger="manual", proc_run_async=False
        )
        self._create_outgoing_move(12)
        reassort_move = self._create_not_started_replenishment_move(
            orderpoint, location_src, 12
        )

        job_func = orderpoint._cancel_fulfilled_replenishment_moves
        with trap_jobs() as trap:
            # stock arrives directly on the orderpoint's location through
            # another route, fulfilling the demand without going through
            # the not-yet-started replenishment move
            self._create_incoming_move(12, self.location_dest)
            trap.assert_jobs_count(1, only=job_func)
            trap.perform_enqueued_jobs()

        reassort_move.invalidate_recordset()
        self.assertEqual(reassort_move.state, "cancel")
        replenish_move = self._get_replenishment_move(orderpoint)
        self.assertEqual(len(replenish_move), 0)

    def test_keep_move_when_demand_remains(self):
        orderpoint, location_src = self._create_orderpoint_complete(
            "Stock2", trigger="manual", proc_run_async=False
        )
        self._create_outgoing_move(12)
        reassort_move = self._create_not_started_replenishment_move(
            orderpoint, location_src, 12
        )

        job_func = orderpoint._cancel_fulfilled_replenishment_moves
        with trap_jobs() as trap:
            # only part of the demand is fulfilled directly, 6 units are
            # still needed: the move must be left untouched
            self._create_incoming_move(6, self.location_dest)
            trap.assert_jobs_count(1, only=job_func)
            trap.perform_enqueued_jobs()

        reassort_move.invalidate_recordset()
        self.assertEqual(reassort_move.state, "confirmed")

    def test_do_not_touch_started_replenishment_move(self):
        orderpoint, location_src = self._create_orderpoint_complete(
            "Stock2", trigger="manual", proc_run_async=False
        )
        self._create_outgoing_move(12)
        reassort_move = self._create_not_started_replenishment_move(
            orderpoint, location_src, 12
        )
        self._create_quants(self.product, location_src, 12)
        reassort_move._action_assign()
        reassort_move.picking_id.printed = True
        self.assertEqual(reassort_move.state, "assigned")

        job_func = orderpoint._cancel_fulfilled_replenishment_moves
        with trap_jobs() as trap:
            self._create_incoming_move(12, self.location_dest)
            trap.assert_jobs_count(1, only=job_func)
            trap.perform_enqueued_jobs()

        reassort_move.invalidate_recordset()
        self.assertEqual(reassort_move.state, "assigned")

    def test_unlink_deletes_picking_when_it_was_the_only_move(self):
        orderpoint, location_src = self._create_orderpoint_complete(
            "Stock2", trigger="manual", proc_run_async=False
        )
        orderpoint.unlink_fulfilled_replenishment_moves = True
        picking_type = orderpoint.route_id.rule_ids.picking_type_id
        picking = self.env["stock.picking"].create(
            {
                "picking_type_id": picking_type.id,
                "location_id": location_src.id,
                "location_dest_id": self.location_dest.id,
            }
        )
        self._create_outgoing_move(12)
        reassort_move = self._create_not_started_replenishment_move(
            orderpoint, location_src, 12, picking_id=picking.id
        )
        move_id = reassort_move.id

        job_func = orderpoint._cancel_fulfilled_replenishment_moves
        with trap_jobs() as trap:
            self._create_incoming_move(12, self.location_dest)
            trap.assert_jobs_count(1, only=job_func)
            trap.perform_enqueued_jobs()

        self.assertFalse(self.env["stock.move"].browse(move_id).exists())
        self.assertFalse(picking.exists())

    def test_unlink_keeps_picking_with_other_moves(self):
        orderpoint, location_src = self._create_orderpoint_complete(
            "Stock2", trigger="manual", proc_run_async=False
        )
        orderpoint.unlink_fulfilled_replenishment_moves = True
        picking_type = orderpoint.route_id.rule_ids.picking_type_id
        picking = self.env["stock.picking"].create(
            {
                "picking_type_id": picking_type.id,
                "location_id": location_src.id,
                "location_dest_id": self.location_dest.id,
            }
        )
        other_product = self.env["product.product"].create(
            {"name": "Other product", "type": "product"}
        )
        other_move = self._create_move(
            "Other move",
            5,
            location_src,
            self.location_dest,
            product=other_product,
            picking_id=picking.id,
        )
        self._create_outgoing_move(12)
        reassort_move = self._create_not_started_replenishment_move(
            orderpoint, location_src, 12, picking_id=picking.id
        )
        move_id = reassort_move.id

        job_func = orderpoint._cancel_fulfilled_replenishment_moves
        with trap_jobs() as trap:
            self._create_incoming_move(12, self.location_dest)
            trap.assert_jobs_count(1, only=job_func)
            trap.perform_enqueued_jobs()

        self.assertFalse(self.env["stock.move"].browse(move_id).exists())
        self.assertTrue(picking.exists())
        self.assertEqual(picking.move_ids, other_move)

    def test_confirming_replenishment_move_does_not_cancel_its_own_backorder(self):
        orderpoint, location_src = self._create_orderpoint_complete(
            "Stock2", trigger="manual", proc_run_async=False
        )
        self._create_outgoing_move(12)
        self._create_quants(self.product, location_src, 12)
        picking_type = orderpoint.route_id.rule_ids.picking_type_id
        picking = self.env["stock.picking"].create(
            {
                "picking_type_id": picking_type.id,
                "location_id": location_src.id,
                "location_dest_id": self.location_dest.id,
            }
        )
        reassort_move = self._create_move(
            "Auto replenishment",
            12,
            location_src,
            self.location_dest,
            location_orderpoint_id=orderpoint.id,
            picking_id=picking.id,
        )
        reassort_move._action_assign()
        self.assertEqual(reassort_move.state, "assigned")
        # only part of the reserved qty is actually delivered: this must
        # create a backorder for the remaining 6 units, not cancel it
        reassort_move.move_line_ids.qty_done = 6

        job_func = orderpoint._cancel_fulfilled_replenishment_moves
        with trap_jobs() as trap:
            picking.with_context(cancel_backorder=False)._action_done()
            trap.assert_jobs_count(0, only=job_func)

        backorder_picking = picking.backorder_ids
        self.assertTrue(backorder_picking)
        backorder_move = backorder_picking.move_ids
        self.assertTrue(backorder_move)
        self.assertNotEqual(backorder_move.state, "cancel")

    def test_checked_regardless_of_orderpoint_trigger(self):
        for trigger in ("auto", "manual", "cron"):
            with self.subTest(trigger=trigger):
                orderpoint, location_src = self._create_orderpoint_complete(
                    f"Stock2-{trigger}", trigger=trigger, proc_run_async=False
                )
                self._create_outgoing_move(12)
                reassort_move = self._create_not_started_replenishment_move(
                    orderpoint, location_src, 12
                )

                job_func = orderpoint._cancel_fulfilled_replenishment_moves
                with trap_jobs() as trap:
                    self._create_incoming_move(12, self.location_dest)
                    trap.assert_jobs_count(1, only=job_func)
                    trap.perform_enqueued_jobs()

                reassort_move.invalidate_recordset()
                self.assertEqual(reassort_move.state, "cancel")
                # keep iterations isolated from each other
                orderpoint.active = False
