# Copyright 2023 Michael Tietz (MT Software) <mtietz@mt-software.de>
# Copyright 2026 ACSONE SA/NV (https://www.acsone.eu)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
from collections import defaultdict
from copy import copy

from odoo import _, api, fields, models, tools
from odoo.exceptions import ValidationError
from odoo.osv import expression
from odoo.tools import split_every
from odoo.tools.safe_eval import safe_eval

from odoo.addons.queue_job.job import identity_exact

from .stock_location_orderpoint_strategy import StockLocationOrderpointStrategy
from .tools import MovesTouchTracker


class StockLocationOrderpoint(models.Model):
    _name = "stock.location.orderpoint"
    _inherit = ["stock.exclude.location.mixin"]
    _description = "Stock location orderpoint"
    _order = "priority desc, sequence"
    _check_company_auto = True

    name = fields.Char(
        copy=False,
        required=True,
        readonly=False,
        default="/",
        help="Set to '/' and save if you want a default name to be proposed.",
    )
    company_id = fields.Many2one(
        "res.company",
        "Company",
        required=True,
        default=lambda self: self.env.company,
    )
    location_id = fields.Many2one(
        "stock.location",
        "Location",
        ondelete="cascade",
        required=True,
        check_company=True,
    )
    trigger = fields.Selection(
        [
            ("auto", "Auto/realtime"),
            ("manual", "Manual"),
            ("cron", "Scheduled"),
        ],
        default="auto",
        required=True,
        help="Auto/realtime orderpoints are triggered on new moves\n"
        "Manual orderpoints are triggered via the orderpoints' view\n"
        "Scheduled orderpoints are triggered via scheduled actions per location",
    )
    replenish_method = fields.Selection(
        [("fill_up", "Fill up")],
        default="fill_up",
        required=True,
        help="Defines how the qty to replenish gets computed\n"
        "Fill up = The replenishment will be triggered when a move is waiting availability "
        "and forecast quantity is negative at the location (i.e. min=0). "
        "The replenished quantity will bring back the forecast quantity to 0 (i.e. max=0) "
        "but will be limited to what is available at the source location "
        "to plan only reservable replenishment moves",
    )
    sequence = fields.Integer(default=10)
    route_id = fields.Many2one(
        "stock.route",
        string="Preferred Route",
        domain="[('rule_ids.location_dest_id', 'in', [location_id])]",
    )
    group_id = fields.Many2one(
        "procurement.group",
        "Procurement Group",
        copy=False,
        help="Moves created through this orderpoint "
        "will be put in this procurement group. "
        "If none is given, the moves generated by stock rules "
        "will be grouped into one big picking.",
    )
    location_src_id = fields.Many2one(
        "stock.location", compute="_compute_location_src_id", store=True
    )
    product_domain_char = fields.Char(
        string="Product domain",
        help="Additional domain to filter products for this orderpoint. ",
        default="[]",
    )
    replenish_limit_to_free_qty = fields.Boolean(
        string="Limit replenishment to free quantity at source location",
        help="If enabled, the replenishment quantity will be "
        "limited to the free quantity at the source location. ",
        default=True,
    )
    replenish_horizon = fields.Float(
        string="Replenishment horizon (in days)",
        help="Time horizon to consider for the replenishment. "
        "Limits the demand considered to what is expected in the horizon. ",
        default=7,
        required=True,
    )
    active = fields.Boolean(default=True)

    last_cron_execution = fields.Datetime(
        help="Last time this orderpoint was processed by the cron",
    )
    priority = fields.Selection(
        selection="_selection_move_priorities",
        default="0",
    )
    proc_run_async = fields.Boolean(
        string="Delay procurement execution",
        help="If enabled, procurements will be run asynchronously in delayed jobs "
        "when processing this orderpoint. Only applies to 'cron' and 'manual' triggers. "
        "If disabled, all procurements will be run in the same transaction. ",
        compute="_compute_proc_run_async",
        store=True,
        readonly=False,
        precompute=True,
    )

    _sql_constraints = [
        (
            "location_route_unique",
            "unique(location_id, route_id, company_id, replenish_method)",
            "The combination of Company, Location, Route and Replenish method must be unique",
        )
    ]

    def _selection_move_priorities(self):
        return self.env["stock.move"]._fields["priority"].selection

    # -------------------------------------------------------------------------
    # Simple properties
    # -------------------------------------------------------------------------

    @property
    def _horizon_datetime(self):
        """Compute the replenishment horizon as a datetime based on the current time and the
        replenish_horizon field expressed in days."""
        self.ensure_one()
        return fields.Datetime.add(fields.Datetime.now(), days=self.replenish_horizon)

    # -------------------------------------------------------------------------
    # Validation and computed fields
    # -------------------------------------------------------------------------

    @api.constrains("location_id", "route_id")
    def _check_location_id_route_id(self):
        for orderpoint in self:
            if (
                not orderpoint.route_id
                or orderpoint.location_id
                in orderpoint.route_id.rule_ids.location_dest_id
            ):
                continue
            raise ValidationError(
                _(
                    "The selected route %(route_name)s must contain "
                    "a rule where the Destination Location is %(location_name)s"
                )
                % {
                    "route_name": orderpoint.route_id.display_name,
                    "location_name": orderpoint.location_id.display_name,
                }
            )

    @api.depends("location_id", "route_id")
    def _compute_location_src_id(self):
        for orderpoint in self:
            location = False
            if orderpoint.location_id and orderpoint.route_id:
                location = orderpoint.location_id._get_source_location_from_route(
                    orderpoint.route_id,
                    "make_to_stock",
                )
            orderpoint.location_src_id = location

    @api.depends("trigger")
    def _compute_proc_run_async(self):
        for orderpoint in self:
            orderpoint.proc_run_async = orderpoint.trigger in ("cron", "manual")

    # -------------------------------------------------------------------------
    # Orderpoint selection and domains
    # -------------------------------------------------------------------------

    def _get_product_domain(self):
        self.ensure_one()
        return safe_eval(self.product_domain_char) if self.product_domain_char else []

    def _prepare_orderpoint_domain_location(
        self, location_ids, location_field="location_id"
    ):
        """
        Returns the domain part of the location selection of _get_orderpoints
        :param list int location_ids: list of stock.location ids
        :param str location_field: location_id or location_src_id
            To create the domain searching the specific location field
        """
        ids = location_ids
        if not isinstance(ids, list):
            ids = ids.ids

        location_field = location_field or "location_id"
        return [(location_field, "parent_of", ids)]

    def _prepare_orderpoint_domain(
        self, trigger, locations=None, location_field="location_id"
    ):
        """Returns the domain for _get_orderpoints"""
        domain = [("trigger", "=", trigger)]
        if locations:
            domain = expression.AND(
                [
                    domain,
                    self._prepare_orderpoint_domain_location(locations, location_field),
                ]
            )
        return domain

    @api.model
    @tools.ormcache(
        "trigger",
        "location_field",
        'tuple(self.env.context.get("allowed_company_ids", []))',
    )
    def _get_ids_by_parent_path(self, trigger, location_field):
        """Returns a dict of orderpoint ids by their parent paths for the given
        trigger and location_field
        """
        orderpoints = self.search(self._prepare_orderpoint_domain(trigger))
        result = defaultdict(list)
        for orderpoint in orderpoints:
            result[orderpoint[location_field].parent_path].append(orderpoint.id)
        return result

    @api.model
    def _get_orderpoints(self, trigger, locations=None, location_field="location_id"):
        """Returns orderpoints selected by trigger, locations and location_field"""
        ids_by_parent_paths = self._get_ids_by_parent_path(trigger, location_field)
        ids = set()
        if locations:
            for location in locations:
                for parent_path in ids_by_parent_paths:
                    if location.parent_path.startswith(parent_path):
                        ids.update(ids_by_parent_paths[parent_path])
        else:
            # ids_by_parent_paths.values() is a list of ids. We need to flatten it
            ids = set().union(*ids_by_parent_paths.values())
        return self.browse(list(ids)).sorted()

    @api.model
    def _get_orderpoints_from_moves(self, moves, trigger="auto"):
        """Return orderpoints impacted by the given move set."""
        orderpoints = self._get_orderpoints(
            trigger, locations=moves.location_id, location_field="location_id"
        )
        return orderpoints | self._get_orderpoints(
            trigger, locations=moves.location_dest_id, location_field="location_src_id"
        )

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_consuming_moves_domain(self, orderpoint_id):
        (
            _q,
            _il,
            domain_move_out_loc,
        ) = self._get_dest_domains(orderpoint_id)
        domain = [
            ("state", "in", ("confirmed", "partially_available")),
        ]
        return expression.AND([domain_move_out_loc, domain])

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_supplying_moves_domain(self, orderpoint_id):
        (
            _q,
            domain_move_in_loc,
            _ol,
        ) = self._get_src_domains(orderpoint_id)
        domain = [
            ("state", "=", "done"),
        ]
        return expression.AND([domain_move_in_loc, domain])

    @api.model
    def _collect_products_by_orderpoint(self, moves, orderpoints, get_moves_domain):
        """Group impacted products by orderpoint using a domain provider."""
        products_by_orderpoint = defaultdict(self.env["product.product"].browse)
        for orderpoint in orderpoints:
            product_domain = orderpoint._get_product_domain()
            if product_domain:
                authorized_product = moves.mapped("product_id").filtered_domain(
                    product_domain
                )
                moves = moves.filtered(lambda m: m.product_id in authorized_product)
            moves_for_orderpoint = moves.filtered_domain(
                get_moves_domain(orderpoint.id)
            )
            if not moves_for_orderpoint:
                continue
            products_by_orderpoint[orderpoint] |= moves_for_orderpoint.product_id
        return products_by_orderpoint

    @api.model
    def _get_from_move_demand(self, moves, trigger="auto"):
        """
        Return a dict of products by orderpoint to replenish the demand
        generated by the given moves. (The given moves are consuming the
        orderpoint location).
        :param moves: stock.move recordset
        :param trigger: the trigger to consider to select the orderpoints to replenish
        :return: dict {orderpoint: products}
        """
        # move from location consume order point location -> DO I've to replenish?
        orderpoints = self._get_orderpoints(
            trigger, locations=moves.location_id, location_field="location_id"
        )
        return self._collect_products_by_orderpoint(
            moves, orderpoints, self._get_consuming_moves_domain
        )

    @api.model
    def _get_from_move_supply(self, moves, trigger="auto"):
        """
        Return a dict of products by orderpoint to replenish the demand
        generated by the given moves. (The given moves are supplying the
        orderpoint source location).
        :param moves: stock.move recordset
        :param trigger: the trigger to consider to select the orderpoints to replenish
        :return: dict {orderpoint: products}
        """
        # move to src location replenish order point source location -> DO I've to replenish?
        orderpoints = self._get_orderpoints(
            trigger, locations=moves.location_dest_id, location_field="location_src_id"
        )
        return self._collect_products_by_orderpoint(
            moves, orderpoints, self._get_supplying_moves_domain
        )

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_src_domains(self, orderpoint_id):
        """Get the quant, move in and move out domains
        for the orderpoint location source and its children locations
        """
        orderpoint = self.browse(orderpoint_id)
        return orderpoint._product_model._get_domain_locations_new(
            [orderpoint.location_src_id.id]
        )

    @api.model
    @tools.ormcache("orderpoint_id")
    def _get_dest_domains(self, orderpoint_id):
        """Get the quant, move in and move out domains
        for the orderpoint location destination and its children locations
        """
        orderpoint = self.browse(orderpoint_id)
        return orderpoint._product_model._get_domain_locations_new(
            [orderpoint.location_id.id]
        )

    # -------------------------------------------------------------------------
    # Context-aware model accessors
    # -------------------------------------------------------------------------

    @property
    def _product_model(self):
        """Returns the product model scoped with the orderpoint's excluded
        location domain."""
        self.ensure_one()
        return self.env["product.product"]

    @property
    def _strategy_model(self) -> StockLocationOrderpointStrategy:
        self.ensure_one()
        if self.replenish_method == "fill_up":
            return self.env["stock.location.orderpoint.strategy.fill_up"]
        raise ValidationError(_("No strategy class available"))

    # -------------------------------------------------------------------------
    # Replenishment computer
    # -------------------------------------------------------------------------

    def _get_replenishment_computer(self):
        """
        Instantiate the replenishment computer in memory for this orderpoint.

        The computer is an orderpoint-agnostic TransientModel (new() — no DB
        persistence) that encapsulates the full demand→procurement_qty pipeline.
        It can equally be instantiated independently of any orderpoint for
        reporting or external integrations.

        The strategy is injected as an instance rather than passing replenish_method,
        so that adding a new strategy never requires modifying the computer.

        :return: stock.location.replenishment.computer in-memory record
        """
        self.ensure_one()
        computer = self.env["stock.location.replenishment.computer"].new(
            self._prepare_replenishment_computer_values()
        )
        computer._strategy = self._strategy_model
        return computer

    def _prepare_replenishment_computer_values(self):
        """Prepare the values to instantiate the replenishment computer."""
        self.ensure_one()
        return {
            "location_id": self.location_id.id,
            "location_src_id": self.location_src_id.id,
            "horizon": self._horizon_datetime,
            "replenish_limit_to_free_qty": self.replenish_limit_to_free_qty,
            "excluded_location_domain": self.stock_excluded_location_domain,
            "product_domain": self._get_product_domain(),
        }

    # -------------------------------------------------------------------------
    # Public triggers and orchestration
    # -------------------------------------------------------------------------

    @api.model
    def run_cron_replenishment(self, location_ids=None):
        orderpoints = self._get_orderpoints(trigger="cron", locations=location_ids)
        res = orderpoints.run_replenishment()
        orderpoints.write({"last_cron_execution": self.env.cr.now()})
        return res

    @api.model
    def run_auto_replenishment(self, products, locations, location_field="location_id"):
        """
        Run the replenishment for all given products.
        Selects the right orderpoints by locations and location_field.

        :param products: browse record list of product.product
        :param locations: browse record list of stock.location
        :param location_field: should be location_id or location_src_id
        """
        if not locations or not products:
            return
        orderpoints = self._get_orderpoints("auto", locations, location_field)
        orderpoints.run_replenishment(products)

    def run_replenishment(self, products=None, job_logs=None):
        """
        Public entry point to execute the replenishment rule.

        :param products: optional recordset of product.product
            If provided, limits the computation scope.
        :param job_logs: optional list to collect trace messages. When provided,
            messages are appended for each step of the pipeline. Used by delayed
            jobs to build their result string.
        """
        result = self.env["stock.move"]
        processed = set()
        for orderpoint in self.sorted():
            result |= orderpoint._run_replenishment(
                products=products, processed=processed, job_logs=job_logs
            )
            processed.update(
                [orderpoint._processed_key(m.product_id.id) for m in result]
            )
        return result

    def _processed_key(self, product_id):
        """Return the deduplication key for one product in this orderpoint context."""
        self.ensure_one()
        return (self.priority, self.location_id.id, product_id)

    def _run_replenishment(self, products=None, processed=None, job_logs=None):
        """
        Internal pipeline:
        1. determine candidate products
        2. via the replenishment computer: compute demand (async) or
           demand + procurement qty (sync) in a single call
        3. either enqueue one job per product (async) or execute immediately (sync)

        Two delay mechanisms coexist in this module:

        - AUTO trigger: delay happens *before* this pipeline in stock.move,
          one job per (orderpoint, product). _must_delay_fulfill_procurement()
          always returns False for AUTO orderpoints so execution is always
          synchronous here.

        - CRON / MANUAL triggers: when proc_run_async is True, demand is
          computed first (demand_only=True), then one job per product is
          enqueued. Each job re-runs the full pipeline autonomously
          (demand_only=False) so that availability and procurement creation
          are always atomic within a single transaction. The number of jobs
          is bounded by the number of products with actual demand.
        """
        result = self.env["stock.move"]
        processed = processed or set()
        self.ensure_one()
        is_delayed = self._must_delay_fulfill_procurement()

        products = self._get_candidate_products(products)

        # Filter out products already handled by a higher-priority orderpoint
        # sharing the same location. Only meaningful in the async path.
        if products is not None and processed and is_delayed:
            products = products.filtered(
                lambda p: self._processed_key(p.id) not in processed
            )

        if not products and products is not None:
            if job_logs is not None:
                job_logs.append(
                    _(
                        "No products to replenish for orderpoint %(orderpoint)s",
                        orderpoint=self.display_name,
                    )
                )
            return result

        # Single call to the computer:
        #   demand_only=True  → returns {product_id: demand_qty}  (async path)
        #   demand_only=False → returns {product_id: qty_to_procure} (sync path)
        computer = self._get_replenishment_computer()
        procurement_data = computer.compute(
            products=products,
            demand_only=is_delayed,
            job_logs=job_logs,
        )

        # Secondary filter on demand_data for the async path when products=None
        # lets the strategy return a broader set than what was pre-filtered above.
        if procurement_data and processed and is_delayed:
            procurement_data = {
                pid: qty
                for pid, qty in procurement_data.items()
                if self._processed_key(pid) not in processed
            }

        if not procurement_data:
            if job_logs is not None:
                job_logs.append(
                    _(
                        "No demand to replenish for orderpoint %(orderpoint)s",
                        orderpoint=self.display_name,
                    )
                )
            return result

        if is_delayed:
            for product_id, demand_qty in procurement_data.items():
                self._enqueue_fulfill_procurement(product_id, demand_qty).delay()
            return result

        if job_logs is not None:
            job_logs.append(
                _(
                    "Running replenishment for orderpoint %(orderpoint)s "
                    "for %(product_count)s products.",
                    orderpoint=self.display_name,
                    product_count=len(procurement_data),
                )
            )

        procurements = self._build_procurements(procurement_data)
        if not procurements:
            return result

        result = self._execute_run_procurements(procurements)
        return self._after_replenishment(result)

    # -------------------------------------------------------------------------
    # Replenishment execution pipeline (orderpoint-bound)
    # -------------------------------------------------------------------------

    def _get_candidate_products(self, products=None):
        """
        Resolve the product scope.

        Priority:
        1. explicit products
        2. strategy override
        3. default (rule-based — to be implemented if needed)

        :return: product.product recordset or None
        """
        self.ensure_one()
        return self._strategy_model._get_candidate_products(
            self.location_id,
            self._horizon_datetime,
            self._get_product_domain(),
            products=products,
        )

    def _build_procurements(self, procurement_data):
        """Build procurement payload from computed quantities by product id."""
        self.ensure_one()
        procurement_vals = self._prepare_procurement_vals()
        return [
            self._prepare_procurement(
                self.env["product.product"].browse(product_id),
                procurement_qty,
                date_planned=False,
                proc_vals=procurement_vals,
            )
            for product_id, procurement_qty in procurement_data.items()
        ]

    def _prepare_procurement_vals(self):
        """Prepare common values for procurement creation."""
        self.ensure_one()
        return {
            "route_ids": self.route_id,
            "date_deadline": False,
            "warehouse_id": self.location_id.warehouse_id,
            "group_id": self.group_id,
            "priority": self.priority or "0",
            "location_orderpoint_id": self.id,
        }

    def _prepare_procurement(self, product, qty, date_planned, proc_vals):
        self.ensure_one()
        proc_vals = copy(proc_vals)
        proc_vals.update(
            {
                "date_planned": date_planned or fields.Datetime.now(),
            }
        )
        return self.env["procurement.group"].Procurement(
            product,
            qty,
            product.uom_id,
            self.location_id,
            self.name,
            self.name,
            self.company_id,
            proc_vals,
        )

    def _execute_run_procurements(self, procurement_values):
        """
        Execute the procurements synchronously and return the created moves.

        Shared by all execution paths:
        - AUTO orderpoints (always synchronous — already inside a queue.job)
        - CRON / MANUAL when proc_run_async is False
        - The delayed job _fulfill_procurement() for async cron/manual runs

        :param procurement_values: list of namedtuple Procurement objects
        :return: recordset of created stock.move
        """
        with MovesTouchTracker() as tracker:
            self.env["procurement.group"].with_context(from_orderpoint=True).run(
                procurement_values, raise_user_error=False
            )
            return self.env["stock.move"].browse(tracker.get_ids()).exists()

    # -------------------------------------------------------------------------
    # Async delegation — cron / manual only
    # -------------------------------------------------------------------------

    def _must_delay_fulfill_procurement(self):
        """
        Returns True when per-product fulfillment should be deferred to
        queue.jobs rather than run synchronously in the current transaction.

        Always False for AUTO orderpoints: they already run inside a queue.job
        enqueued by stock.move (_enqueue_run_replenishment). A second delay
        would create a superfluous job chain with no benefit.

        For CRON / MANUAL, follows proc_run_async unless force_sync is set
        in the context (used by _fulfill_procurement to re-enter the pipeline
        synchronously from within a worker).
        """
        self.ensure_one()
        if self.trigger == "auto":
            return False
        if "force_sync" in self.env.context:
            return not self.env.context["force_sync"]
        if "queue_job__no_delay" in self.env.context:
            return not self.env.context["queue_job__no_delay"]
        return self.proc_run_async

    def _enqueue_fulfill_procurement(self, product_id, demand_qty, **job_options):
        """
        Enqueue a delayed job to fulfill the procurement for one product.

        Used exclusively by cron and manual triggers when proc_run_async is True.
        The actual work is performed by _fulfill_procurement().

        Note: demand_qty is passed for the job description only. The job
        recomputes everything autonomously to stay independent of the calling
        transaction's state.

        :param product_id: ID of the product to fulfill
        :param demand_qty: indicative demanded qty — used for job description only
        :param job_options: extra options forwarded to the job (priority, …)
        :return: a Job instance (not yet delayed — caller must call .delay())
        """
        job_options = job_options.copy()
        job_options.setdefault(
            "description",
            _(
                "Try to fulfill procurement for product %(product_name)s in location "
                "%(location_name)s for a demand of %(demand_qty)s with priority %(priority)s",
                product_name=self.env["product.product"]
                .browse(product_id)
                .display_name,
                location_name=self.location_id.display_name,
                demand_qty=demand_qty,
                priority=self.priority or "0",
            ),
        )
        job_options.setdefault("identity_key", identity_exact)
        delayable = self.env[self._name].delayable(**job_options)
        return delayable._fulfill_procurement(
            self.priority, self.location_id.id, product_id
        )

    @api.model
    def _fulfill_procurement(self, priority, location_id, product_id):
        """
        Fulfill the procurement for a single product at a given location and priority.

        Looks up all non-AUTO orderpoints matching (location, priority) and runs
        the full replenishment pipeline synchronously for the given product.
        The pipeline re-runs demand computation from scratch inside this transaction,
        guaranteeing that demand, availability check, and procurement execution are
        all atomic and independent of any prior state.

        This is the queue.job entry point for async cron/manual runs, but its
        contract is independent of that context.

        :param priority: procurement priority string to match orderpoints with
        :param location_id: stock.location id to match orderpoints with
        :param product_id: product.product id to fulfill
        :return: a human-readable summary string (stored as the job result)
        """
        job_logs = []
        orderpoints = self.search(
            [
                ("priority", "=", priority),
                ("location_id", "=", location_id),
                ("trigger", "!=", "auto"),
            ]
        )
        if not orderpoints:
            job_logs.append(
                _(
                    "No orderpoints found for location %(location_name)s "
                    "with priority %(priority)s",
                    location_name=self.env["stock.location"]
                    .browse(location_id)
                    .display_name,
                    priority=priority or "0",
                )
            )
            return "\n".join(job_logs)

        product = self.env["product.product"].browse(product_id)
        result = orderpoints.with_context(force_sync=True).run_replenishment(
            products=product,
            job_logs=job_logs,
        )
        job_logs.append(
            _(
                "Fulfilled procurement for product %(product_name)s "
                "in location %(location_name)s: %(move_count)s replenishment moves created.",
                product_name=product.display_name,
                location_name=orderpoints[0].location_id.display_name,
                move_count=len(result),
            )
        )
        return "\n".join(job_logs)

    # -------------------------------------------------------------------------
    # Post-processing of replenishment moves
    # -------------------------------------------------------------------------

    def _after_replenishment(self, replenishment_moves):
        """Assigns generated replenishment moves and updates picking priorities."""
        self._assign_replenishment_moves(
            replenishment_moves.filtered(lambda m: m.state != "assigned")
        )
        picking_priority_to_update = self.env["stock.picking"]
        for move in replenishment_moves.sudo():
            new_priority = move.location_orderpoint_id.priority
            if move.priority != new_priority:
                move.priority = new_priority
                picking_priority_to_update |= move.picking_id
        for picking in picking_priority_to_update:
            new_priority = max(
                picking.move_ids.filtered(lambda m: m.state != "cancel").mapped(
                    "priority"
                )
            )
            if picking.priority != new_priority:
                # Protect individual move priority from being overridden by
                # the picking's priority recalculation.
                with self.env.protecting(
                    [self.env["stock.move"]._fields["priority"]], picking.move_ids
                ):
                    picking.priority = new_priority

        return self._strategy_model._after_run_replenishment(
            self.location_id, replenishment_moves
        )

    def _assign_replenishment_moves(self, moves_to_assign):
        """Assigns moves created by the orderpoints."""
        for moves_chunk in split_every(100, moves_to_assign.ids):
            self.env["stock.move"].browse(moves_chunk)._action_assign()
        return moves_to_assign

    # -------------------------------------------------------------------------
    # Cache lifecycle and overrides of create/write/unlink
    # -------------------------------------------------------------------------

    def _clear_caches(self):
        self._get_ids_by_parent_path.clear_cache(self)
        self._get_consuming_moves_domain.clear_cache(self)
        self._get_supplying_moves_domain.clear_cache(self)
        self._get_src_domains.clear_cache(self)
        self._get_dest_domains.clear_cache(self)

    @api.model_create_multi
    def create(self, vals_list):
        self._clear_caches()
        val_list_updated = []
        for vals in vals_list:
            if "name" not in vals or vals["name"] == "/":
                val_list_updated.append(
                    dict(
                        vals,
                        name=self.env["ir.sequence"].next_by_code(
                            "stock.location.orderpoint"
                        ),
                    )
                )
            else:
                val_list_updated.append(vals)
        return super().create(val_list_updated)

    def write(self, vals):
        self._clear_caches()
        if "name" in vals and vals["name"] == "/":
            vals["name"] = self.env["ir.sequence"].next_by_code(
                "stock.location.orderpoint"
            )
        return super().write(vals)

    def unlink(self):
        self._clear_caches()
        return super().unlink()
