# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Stock Location Orderpoint Cleanup",
    "summary": """
        This module allows to clean moves generated by orderpoint""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV,Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/stock-logistics-orderpoint",
    "depends": ["base_partition", "stock_location_orderpoint", "queue_job"],
    "data": [
        "security/security.xml",
        "wizards/stock_location_orderpoint_cleanup.xml",
        "views/stock_location_orderpoint.xml",
    ],
}
