# Copyright 2023 ACSONE SA/NV
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Stock Location Orderpoint Dynamic Routing Merge",
    "summary": """
        Allows to merge the new moves generated by orderpoints in combination
        with dynamic routing""",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "author": "ACSONE SA/NV,Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/stock-logistics-orderpoint",
    "depends": [
        "stock_dynamic_routing",
        "stock_location_orderpoint",
    ],
}
