[project]
name = "odoo-addons-oca-stock-logistics-orderpoint"
version = "18.0.20250609.0"
dependencies = [
    "odoo-addon-stock_orderpoint_default_location==18.0.*",
    "odoo-addon-stock_orderpoint_move_link==18.0.*",
    "odoo-addon-stock_orderpoint_purchase_link==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
